input:
  generate:
    mapping: |
      root = { "amount": 20, "currency": "USD" }
    count: 1

pipeline:
  processors:
    - cue_eval:
        dir: ./cue-processor/cueball
        package: "main"
        fill_path: "usage"
        selector: "fee"

output:
  switch:
    cases:
      - check: errored()
        output:
          drop: {}
          processors:
            - log:
                message: "failed to process message: ${! error() }"
                level: ERROR
      - output:
          stdout: {}
